# Generated by Django 2.0 on 2019-03-20 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190315_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=255, verbose_name='访问者IP')),
                ('is_routable', models.BooleanField(verbose_name='是否是可路由')),
                ('access_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article')),
            ],
            options={
                'verbose_name': '文章访问统计',
                'verbose_name_plural': '文章访问统计',
            },
        ),
    ]
