# Generated by Django 2.0 on 2019-07-07 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190707_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='cover',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_tool', to=settings.FILER_IMAGE_MODEL, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('LINK', '图片链接'), ('TEXT', '文本'), ('BASE64', 'Base64图片')], default=None, max_length=55, null=True, verbose_name='封面类型'),
        ),
    ]
