# Generated by Django 2.0 on 2019-07-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190707_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='cover_type',
        ),
    ]
