# Generated by Django 2.0 on 2019-07-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_tool_cover_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='detail',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name='详细(使用)介绍'),
        ),
    ]
