# Generated by Django 2.0 on 2019-07-07 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190707_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytools',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorytools',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='toolcategory',
            name='tools',
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ToolCategory'),
        ),
        migrations.DeleteModel(
            name='CategoryTools',
        ),
    ]
